group: edge
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t rileyschuit/rpi-docker-s3cmd .
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    #TAG=$(TODO)
    #docker tag rileyschuit/rpi-docker-s3cmd rileyschuit/rpi-docker-s3cmd:$TAG
    #docker push rileyschuit/rpi-docker-s3cmd:$TAG
    docker push rileyschuit/rpi-docker-s3cmd
  fi
